
name: Called by Curl

on:
  workflow_dispatch:
    inputs:
      build_cmd:
        description: 'My build command'

      test_cmd:
        description: 'My test command'
        
jobs:

  deal-with-inputs:
    runs-on: [self-hosted]
    steps:

      - run: echo "actions-minion"

      - name: Build command
        run: |
          echo "${{ github.event.inputs.build_cmd }}"

      - name: Test command
        run: |
          echo "${{ github.event.inputs.test_cmd }}"